Login api setup
shinya0226/kensyu pull request #19
Opened 2023-11-30 07:24 UTC by shinya0226

2023-12-04 05:46 UTC, tarokamikaze requested changes
- `infra/mysql/mysql.go` に、山本さんのローカルでしか動かないようなコード(.envファイルのフルパス)が記述されています。環境に依存しない記述を心がけてください。（せめて桑田のローカル環境で動くような記述をするようにしてください）
- `infra/mysql/user.go` に　「// todo 以下でSQL インジェクションが発生しうるかを調査してください」というコメントがありますが、こちらの結果はどうでしたか。コメントに追記したうえで todoの文字を削除してください。

2023-12-04 05:46 UTC, tarokamikaze commented on handler/handler_test.go
> +	testMock.Login(userEntity)
handler.Login() を実行していないように見えます。handler.Login() の結果をテストしてください。

2023-12-04 05:46 UTC, tarokamikaze commented on fixture/fixture.json
> +		{"Email": "Emailは違います", "Password": "yamamo10", "WantErr": true},
- これは本当にfixture dataですか？どうやってローカル環境を立ち上げ、どのツールを使ってこのfixture data を流し込めるのかの手順も README.md に記述してください。
- これが本物のfixture data ならば、 `hash化後の` passwordが上記fixtureと合致するはずですが、テスト等を見てもそのような記述はありません。そもそもhash化後のパスワードが、こんなわかりやすい文字列になるはずがありません。となると、プログラムの記述が間違っているように見えます。

2023-12-06 02:36 UTC, merged

2023-12-06 07:14 UTC, tarokamikaze commented on README.md
>  #環境構築手順として.env.exampleファイルをコピーして .env ファイルを生成すること
`.env` を直接commitしてしまっているので、これはgit管理外にするよう削除してください。
`.gitignore` ファイルに `.env` を追記すると、「ローカルファイルは存在するけどgitリポジトリ管理外である」状態を作れます。

2023-12-06 07:15 UTC, tarokamikaze commented on README.md
> +1.user.goのDBのselect文内のtableをuserからtestに変える。
昨日も口頭でお伝えしましたが、テストのために環境を変える場合、ソースコードに影響する変更（=テーブル名の変更）はやりたくありません。2.のDB変更だけで動くようにしてください。

2023-12-06 07:16 UTC, tarokamikaze commented on infra/mysql/mysql.go
> +	err := godotenv.Load("../../.env")
環境変数は実行時に読めばいいので、ソース内では読まないようにしてほしいです。
[direnv](https://qiita.com/kompiro/items/5fc46089247a56243a62) をローカルでインストールすれば、上記のコードは不要になるはずです。

2023-12-06 07:17 UTC, tarokamikaze commented on infra/mysql/user.go
> +	err := godotenv.Load("../../.env")
direnvを使う方針にしていただき、上記は削除お願いします

2023-12-06 07:17 UTC, tarokamikaze commented on testdata/fixtures/test.yml
> +  Password: "yamamo10"
前のPRでもお伝えしましたが、パスワードが平文っぽく見えます。ハッシュ化されていないと正しく動かないはずです。

2023-12-06 07:20 UTC, tarokamikaze commented on infra/mysql/user.go
> +	if err := ur.db.QueryRow("SELECT * FROM test WHERE Email = ?", email).
テーブル名が `test` ですが、 userが正しいですよね？

2023-12-06 07:22 UTC, tarokamikaze commented on handler/handler_test.go
> +	testMock.Login(userEntity)
`handler.Login()` の引数は `testMock` ではないですか？　また、 `testMock.Login(userEntity)`　は不要に見えます。
せっかく作ったmockインスタンスを活用していないように見えます。

2023-12-07 08:26 UTC, shinya0226 commented on handler/handler_test.go
> +	testMock.Login(userEntity)
[https://qiita.com/gold-kou/items/81562f9142323b364a60](url)
こちらを参考にすると、testMock.Login(userEntity)を使っているように思われます。

2023-12-08 01:07 UTC, shinya0226 commented on testdata/fixtures/test.yml
> +  Password: "yamamo10"
こちらの処理はサインアップAPIの実装時に追加する方向で良いでしょうか？