login api setupからの引き継ぎ
shinya0226/kensyu pull request #20
Opened 2023-12-08 01:20 UTC by shinya0226

桑田さんのレビューの修正を行いました。
ご確認お願いします。

2023-12-11 07:19 UTC, tarokamikaze requested changes
* migration実行方法やツールのインストール手順も、環境構築手順としてREADME.md に記述すべき内容です。記述してください
* `.env` を使うべきなのか、 `.envrc` を使うべきなのかはっきりさせてください。README.md の記述も正しいやり方にそろえてください。
* テストだとしても、テーブル名は変更しないでください。migrationと不整合がおきます。
* テストがこけました。fixtureがおかしいです。
   * testdata/fixtures/test.yml -> testdata/fixtures/users.yml
* マージ先をmainブランチに変更してください。

2023-12-19 06:38 UTC, tarokamikaze requested changes
60点まで来てます！Goodです！
せっかくなので100点を目指していきましょう！！

2023-12-19 06:38 UTC, tarokamikaze commented on .github/PULL_REQUEST_TEMPLATE.md
> +## JIRA Issue
次回からでいいので、以下に従ってPull Request の Descriptionを書いてみてください

2023-12-19 06:38 UTC, tarokamikaze commented on handler/handler_test.go
> +			Entity:      `{"email":"shinya.yamamoto6@persol-pt.co.jp","password":"yamamo10","name":"山本真也","isAdmin":0}`,
口頭でもお伝えしましたが、

* Entity, Wantは structで定義したほうが楽です。responseとの比較は `json.Decode()` した結果のインスタンス同士でやるといいです。
* http Respose Code もテストしてください。
* mockの動作を各tableで定義することで、柔軟なテストが可能になります。
* `handler.Login()` の返り値のfunctionを実行することで、handler全体をテストすることができます

2023-12-19 06:38 UTC, tarokamikaze commented on handler/handler_test.go
> +			ctrl := gomock.NewController(t)
`defer ctrl.Finish()` して、メソッドが期待どおりに叩かれているかをテストできることも確認してください

2023-12-19 06:38 UTC, tarokamikaze commented on infra/mysql/mysql.go
> +	db, _ := sql.Open("mysql", "atsuser:atspass@tcp(localhost:3306)/kensyu_testing?parseTime=true")
いつのまにか、環境変数を無視する書き方に戻っていませんか？
環境変数を使ってDBにアクセスするようにしてください。

2023-12-19 06:38 UTC, tarokamikaze commented on infra/mysql/user.go
> +	db.Close()
`ur.db` を利用しているなら、上記 `db` は不要では。削除してください

2023-12-19 06:38 UTC, tarokamikaze commented on usecase/usecase.go
>  func VerifyPassword(hashedPassword string, entryPassword string) error {
リファクタした結果、 `VerifyPassword()` と `CreateToken()` はglobalに晒す必要がなくなったので、最初の一字を小文字にしましょう

2023-12-19 06:38 UTC, tarokamikaze commented on infra/mysql/user_test.go
>  			prepareTestDatabse()
typo. `prepareTestDatabase` が正しい

2023-12-19 06:38 UTC, tarokamikaze commented on infra/mysql/user.go
> +const FixturesPathSQL = "../../testdata/fixtures"
使っていない行なので消しましょう

2023-12-21 06:29 UTC, shinya0226 commented
## JIRA Issue

- [HMX-xxx](https://seedscompany.atlassian.net/browse/HMX-xxx)

## 変更の概要

- 現状の問題点
- この変更が解決すること
- ...

## 今回保留にした内容

- 今回は保留にしたが、今後対応しなければならないこと
- ストーリー、タスクが作成されてなかったら、作業者に作成してもらってください
- ...

## レビューの前提条件

- 知らないとレビューに支障があること
- 失敗しても問題ない単体テスト
- テスト環境の変更（migrationや環境変数の追加など）
- ...

## テスト項目

- [ 真流] [コーディング方針](https://seedscompany.atlassian.net/wiki/spaces/SXP/pages/5355700940/OPEN+backend)に沿っている
- [✔︎] CIエラーがないこと
- [✔︎] 動作確認

## 関連URL

- 参考にしたリソース
- Confluenceの関連ドキュメント
- ...

## 備考

- レビュワーに対する注意点など
- ...
- ...

2024-01-04 08:41 UTC, tarokamikaze requested changes
概ねOKです！あと一歩！

2024-01-04 08:41 UTC, tarokamikaze commented on infra/mysql/user.go
> +	if err := ur.db.QueryRow("SELECT * FROM"+" "+table+" "+"WHERE Email = ?", email).
SQLをプログラム上で書くときは、文字列連結は厳禁です。なぜなら、SQLインジェクションが入る温床になるから。
go test とローカル実行時でデータを分けたいときは、テーブルを変えるのではなく、DBを変えるのが王道です。
なので、環境変数 `DB_TABLE` 自体が不要なはず。

2024-01-04 08:41 UTC, tarokamikaze commented on handler/handler.go
> +		return c.String(http.StatusNotFound, "Emailは見つかりません")
正常系のresponseがjsonである以上、エラー時のメッセージも単なる文字列ではなくjsonで返すべきです。以下みたいな単純な形でよいので。
```
{ "error": "xxxxxx" }
```

また慣例として、エラーメッセージを日本語で返すケースはほとんどありません。英語で返しましょう。

これは必須ではないですが、DBが落ちた等のログが現状だと握りつぶされてしまい、確認できません。もしユーザー起因のエラーでなければ、 response code 500 を返し、 `log.Printf()` でサーバーにアプリケーションログを残すのが王道。

2024-01-04 08:41 UTC, tarokamikaze commented on README.md
> +migrate -source file://./migrations/users/ -database 'mysql://${DB_USER}:${DB_PASS}@tcp(${DB_HPST}:${DB_PORT})/${DB_NAME}' up
- シングルクォートだと変数が埋め込まれません。ダブルクォートに変更すれば動きます。
- `DB_HPST` は `DB_HOST` のtypoですね
- クワタのローカルだとデータがないので、動作確認が完了できませんでした。fixtureを投入する手段を用意し、投入手順をREADME.md に記述してください。
  - fixture投入するだけのmain.go を別途用意するのがいいかも
- ついでに、サーバーを起動するコマンドが記述されていないので、それも書きましょう

2024-01-04 08:41 UTC, tarokamikaze commented on README.md
> +#fixtureにてテストを実行する際はfix_testデータベースにてusersテーブルを使用する。
この一文はもはや不要では。記述を全体的に最新化してください。

2024-01-05 05:47 UTC, shinya0226 commented
## JIRA Issue

- [YIN-39](https://seedscompany.atlassian.net/browse/YIN-39)

## 変更の概要

- SQL文の修正
- 正常なエラーメッセージの表示
- READMEの修正

- 現状の問題点
- 特になし

## 今回保留にした内容

- 特になし

## レビューの前提条件

- 特になし

## テスト項目

- [　] [コーディング方針](https://seedscompany.atlassian.net/wiki/spaces/SXP/pages/5355700940/OPEN+backend)に沿っている
- [　] CIエラーがないこと
- [　] 動作確認
- 下記動作確認に問題がないこと

## 動作確認手順

- [　] ` curl -X POST -H "Content-Type: application/json" -d '{"Email":"rio.matumoto@persol-pt.co.jp", "Password":"rio3"}' http://localhost:8080/login` を実行して、`{"email":"rio.matumoto@persol-pt.co.jp","name":"松本莉央","isAdmin":1,"access_token":"有効期限1時間のアクセストークン"}` が返ってくる。
- [　]  ` curl -X POST -H "Content-Type: application/json" -d '{"Email":"Emailは違うよ", "Password":"rio3"}' http://localhost:8080/login`を実行して、`{"message":"Internal Server Error"}`が返ってくる。
- [　]  `curl -X POST -H "Content-Type: application/json" -d '{"Email":"", "Password":""}' http://localhost:8080/login `
 を実行して、`{"message":"Internal Server Error"}`が返ってくる。

## 関連URL

- https://echo.labstack.com/docs/testing

## 備考

- 特になし

2024-01-05 06:27 UTC, tarokamikaze requested changes
* `tool/main.go` は不要なので消してください。
* 動作確認において、ログイン成功時に、氏名が正しく表示されませんでした。以下のように帰ってきます。氏名をきちんと表示できるようにしてください。

```
$ curl -X POST -H "Content-Type: application/json" -d '{"Email":"rio.matumoto@persol-pt.co.jp", "Password":"rio3"}' http://localhost:8080/login | jq .

{
  "email": "rio.matumoto@persol-pt.co.jp",
  "name": "????",
  "isAdmin": 1,
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQ0MzkzNjksInVzZXIiOiJyaW8ubWF0dW1vdG9AcGVyc29sLXB0LmNvLmpwIn0.Fvg7bfGYpUIRFhbT3Pj22iQVI9Jds91YAImezPBODSI"
}
```

2024-01-05 06:30 UTC, tarokamikaze commented
ヒント。クワタのローカルDBに対して↓のSQLを実行した結果。

```
show create table users;
```

```
CREATE TABLE `users` (
  `Email` varchar(255) NOT NULL,
  `Password` varchar(255) NOT NULL,
  `Name` varchar(255) NOT NULL,
  `IsAdmin` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

2024-01-05 07:57 UTC, tarokamikaze approved these changes
![LGTM](https://images.lgtmgen.org/06a0609d-3f25-44b5-81c0-1b98587cc9c0)

おつかれさまでした！！！！！

2024-01-05 08:01 UTC, merged