Accountlist api
shinya0226/kensyu pull request #31
Opened 2023-12-26 03:34 UTC by shinya0226

## JIRA Issue

- [HMX-xxx](https://seedscompany.atlassian.net/browse/HMX-xxx)

## 変更の概要

- 現状の問題点
- 
- ..

## 今回保留にした内容

- 
-

## レビューの前提条件

-

## テスト項目

- [✔︎ ] [コーディング方針](https://seedscompany.atlassian.net/wiki/spaces/SXP/pages/5355700940/OPEN+backend)に沿っている
- [✔︎] CIエラーがないこと
- [✔︎] 動作確認

## 関連URL
- https://echo.labstack.com/docs/testing

## 備考
-

2024-01-16 03:40 UTC, tarokamikaze requested changes
- API仕様書のリンクをPRコメントに貼ってください
- 動作確認手順が不足しています
   - adminでないユーザーがアクセスした場合 
   - ログインなしでアクセスした場合
   - `page` に文字列が追加された場合
   - `page` に2ページ目以降の数値が入れられたときに、正しくページングが動作するか

2024-01-16 03:40 UTC, tarokamikaze commented on handler/handler.go
> +func Allowed(c echo.Context) error {
よくわかっていないんですが、このhandlerって必要なんでしたっけ。

2024-01-16 03:40 UTC, tarokamikaze commented on handler/handler.go
> +func FetchAccounts() echo.HandlerFunc {
今後もhandlerが増えることを考えると、 このファイルにすべての handler を書くのは管理上面倒になるかもしれません。一般的なプログラミングの流派でいうと以下があります。ご自身で判断して、方針を決めてみてください。

- 今のまま、可能な限り1ファイルでまとめる: 2010年中旬ごろのgolang使いでは、これが美徳とされていたらしい。最近はそうでもない。
- `handler/accounts/fetch.go`, `handler/accounts/login.go` 等、扱う対象でディレクトリを分け、ハンドラー毎にファイルを分ける: 細かくはなるが変更範囲が明確になるのでレビュアーに優しい。x:eee/アルネクはこの方式。
   - これでやる場合、golangの流儀として `package名と重複する関数命名はしない` というものがあるので、 `FetchAccounts()`  ではなく `Fetch()` で書くべきです
- `handler/accounts.go`, `handler/todo.go` 等,URL/扱う対象毎でファイルを分ける: RubyOnRails等、MVCの考え方に近い。2010年代前半の主流。いまでも古くはない。

2024-01-16 03:40 UTC, tarokamikaze commented on handler/handler.go
> +		page := c.Param("page")
- echo.Context から必要情報を取得したら、後続処理はusecaseに移譲してください。clean archtectureでやるということだったので。
- DB操作関連は `infra/mysql` 以下に記述してください。
- ファイル名やURL, テーブル名等が `user` と `account` の双方存在していてややこしいです。同じものを指すのであれば、同じ名前に統一してください

2024-01-16 03:40 UTC, tarokamikaze commented on handler/handler.go
> +			return err
- responseにエラーを帰す場合、この書き方できちんとjson型でresponseできますか？

2024-01-16 03:40 UTC, tarokamikaze commented on handler/handler.go
> +		i, _ = strconv.Atoi(page)
`page` に数字以外の文字列が入れられた場合はbad request error を返すべきです

2024-01-16 03:40 UTC, tarokamikaze commented on handler/handler_test.go
> +	assert.Equal(t, http.StatusOK, rec.Code)
- status code だけでなく、response body も確認しましょう
- 全体的にテストケースが足りていないと思います。table test でいろいろ試しましょう。※usecase層でやるべきものもあると思いますが
   - adminでないユーザーがアクセスした場合 ※middlewareで担保できるならテスト不要
   - ログインなしでアクセスした場合 ※middlewareで担保できるならテスト不要
   - `page` に文字列が追加された場合
   - `page` に2ページ目以降の数値が入れられたときに、正しくページングが動作するか

2024-01-16 03:52 UTC, shinya0226 commented
## JIRA Issue

- [YIN-36](https://seedscompany.atlassian.net/browse/YIN-36)

## API仕様書

https://seedscompany.atlassian.net/wiki/spaces/~712020eb6ef907a9d14b6e8119208cd02dac12/pages/5689639249/API

## CircleCI
https://app.circleci.com/pipelines/github/shinya0226/kensyu/647/workflows/0e23f1b5-da74-4b9e-bfa9-ae93f6a119fa


## 変更の概要

- アカウント一覧情報を取得するためのAPIの作成を開始した。
- JWT認証およびAdmin認証を導入し、ログイン処理によってアクセストークンによる認証を実現し、Admin認証によって管理者権限のあるユーザーのみがアクセスできるようにした。
- ページング処理によって一度に検索できるユーザーの上限を5個に設定している。

## 現状の問題点

- 特になし

## 今回保留にした内容

- 特になし

## レビューの前提条件

- 特になし

## テスト項目

- [　] [コーディング方針](https://seedscompany.atlassian.net/wiki/spaces/SXP/pages/5355700940/OPEN+backend)に沿っている
- [　] CIエラーがないこと
- [　] 動作確認
- 下記動作確認に問題がないこと

## 動作確認手順

- [　] ` go run server/main.go`を実行してサーバを立ち上げる。
- [　] ` curl -X POST -H "Content-Type: application/json" -d '{"Email":"rio.matumoto@persol-pt.co.jp", "Password":"rio3"}' http://localhost:8080/login` を実行して、`{"email":"rio.matumoto@persol-pt.co.jp","name":"松本莉央","isAdmin":1,"access_token":"有効期限1時間のアクセストークン"}` が返ってくる。
- [　]  `curl -H 'Authorization:Bearer "上記ログイン時に得られるアクセストークン"' http://localhost:8080/allowed/accounts/1 `を実行して、`[{"email":"shinya.yamamoto6@persol-pt.co.jp","password":"","name":"山本真也","isAdmin":0},{"email":"kentaro.suzuki@persol-pt.co.jp","password":"","name":"鈴木健太郎","isAdmin":0},{"email":"rio.matumoto@persol-pt.co.jp","password":"","name":"松本莉央","isAdmin":1},{"email":"tsutom.utida@persol-pt.co.jp","password":"","name":"内田勉","isAdmin":0},{"email":"kyousuke.mizuno@persol-pt.co.jp","password":"","name":"水野京介","isAdmin":1}]` が返ってくる。
- [　]  `curl -H 'Authorization:Bearer "間違ったアクセストークン"' http://localhost:8080/allowed/accounts/1 `を実行して、`{"message":"invalid or expired jwt"}`が返ってくる。
- [　]  `curl -H 'Authorization:Bearer "ログイン時に得られるアクセストークン"' http://localhost:8080/allowed/accounts/"存在しないページ" `を実行して、`[　]`が返ってくる。

## 関連URL

- https://echo.labstack.com/docs/request
- https://echo.labstack.com/docs/testing

## 備考

- 特になし

2024-01-16 06:59 UTC, shinya0226 commented on handler/handler.go
> +func Allowed(c echo.Context) error {
不要なので削除しました。

2024-01-16 07:10 UTC, shinya0226 commented on handler/handler.go
> +			return err
現状では、サーバエラーに関してはlog.Printfで記録を残しerrを返し、クライアントエラーの場合はjson型でエラーメッセージを返す方針でやっています。

2024-01-17 02:56 UTC, shinya0226 commented on handler/handler.go
> +func FetchAccounts() echo.HandlerFunc {
x:eee/アルネクの方式で進めることにしました。

2024-01-17 03:02 UTC, shinya0226 commented on handler/handler.go
> +		page := c.Param("page")
ファイル名やURL, テーブル名等を`user`に統一しました。

2024-01-29 02:53 UTC, closed without merging