Userlist api
shinya0226/kensyu pull request #40
Opened 2024-01-17 03:51 UTC by shinya0226

## JIRA Issue

- [HMX-xxx](https://seedscompany.atlassian.net/browse/HMX-xxx)

## 変更の概要

- 現状の問題点
- この変更が解決すること
- ...

## 今回保留にした内容

- 今回は保留にしたが、今後対応しなければならないこと
- ストーリー、タスクが作成されてなかったら、作業者に作成してもらってください
- ...

## レビューの前提条件

- 知らないとレビューに支障があること
- 失敗しても問題ない単体テスト
- テスト環境の変更（migrationや環境変数の追加など）
- ...

## テスト項目

- [ ] [コーディング方針](https://seedscompany.atlassian.net/wiki/spaces/SXP/pages/5355700940/OPEN+backend)に沿っている
- [ ] CIエラーがないこと
- [ ] 動作確認
- [ ] その他テスト環境でレビュワーに確認してほしいこと
- [ ] ...

## 関連URL

- 参考にしたリソース
- Confluenceの関連ドキュメント
- ...

## 備考

- レビュワーに対する注意点など
- ...
- ...

2024-01-24 02:34 UTC, tarokamikaze commented on infra/mysql/users/fetch.go
> +type fetchRepository struct {
`fetchRepository` と `userRepository` はおなじ `User` Entityを扱っているので、ひとつにまとまったほうがわかりやすいと思います。 `userRepository` に統一しませっか。

2024-01-24 02:36 UTC, tarokamikaze requested changes
ざっと見た感じ、プログラム設計上大きな問題はなさそうに見えます。
並行して精読・動作確認を行うので、いったんこの修正だけお願いします！

2024-01-26 01:13 UTC, jusui-ppt commented on entity/users/users.go
> -package entity
コメントテスト

2024-01-27 13:36 UTC, shinya0226 commented on handler/users/login.go
> +		return c.JSON(http.StatusNotFound, err)
仕様書に合わせる方向で行きます。

2024-01-27 14:04 UTC, shinya0226 commented
## JIRA Issue

- [YIN-36](https://seedscompany.atlassian.net/browse/YIN-36)

## API仕様書

https://seedscompany.atlassian.net/wiki/spaces/~712020eb6ef907a9d14b6e8119208cd02dac12/pages/5689639249/API

## CircleCI
https://app.circleci.com/pipelines/github/shinya0226/kensyu/876/workflows/cdbd62ee-888b-4344-81e3-2491231ed38c


## 変更の概要

- レビューの修正

## 現状の問題点

- 特になし

## 今回保留にした内容

- 特になし

## レビューの前提条件

- 特になし

## テスト項目

- [ ] [コーディング方針](https://seedscompany.atlassian.net/wiki/spaces/SXP/pages/5355700940/OPEN+backend)に沿っている
- [ ] CIエラーがないこと
- [ ] 動作確認
- 下記動作確認に問題がないこと

## 動作確認手順

- [x] ` go run server/main.go`を実行してサーバを立ち上げる。

- Admin権限があるユーザーがログインしたとき

- [x] ` curl -X POST -H "Content-Type: application/json" -d '{"Email":"rio.matumoto@persol-pt.co.jp", "Password":"rio3"}' http://localhost:8080/login` を実行して、`{"email":"rio.matumoto@persol-pt.co.jp","name":"松本莉央","isAdmin":1,"access_token":"有効期限1時間のアクセストークン"}` が返ってくる。
- [x]  `curl -H 'Authorization:Bearer "上記ログイン時に得られるアクセストークン"' http://localhost:8080/allowed/users/1 `を実行して、`[{"email":"shinya.yamamoto6@persol-pt.co.jp","password":"","name":"山本真也","isAdmin":0},{"email":"kentaro.suzuki@persol-pt.co.jp","password":"","name":"鈴木健太郎","isAdmin":0},{"email":"rio.matumoto@persol-pt.co.jp","password":"","name":"松本莉央","isAdmin":1},{"email":"tsutom.utida@persol-pt.co.jp","password":"","name":"内田勉","isAdmin":0},{"email":"kyousuke.mizuno@persol-pt.co.jp","password":"","name":"水野京介","isAdmin":1}]` が返ってくる。
- [x]  `curl -H 'Authorization:Bearer "上記ログイン時に得られるアクセストークン"' http://localhost:8080/allowed/users/2`を実行して、`[{"email":"makoto.ueda@persol-pt.co.jp","password":"","name":"上田誠","isAdmin":0},{"email":"satoshi.ono@persol-pt.co.jp","password":"","name":"大野智","isAdmin":1}] `が返ってくる。
- [x]  `curl -H 'Authorization:Bearer "間違ったアクセストークン"' http://localhost:8080/allowed/users/1 `を実行して、`{"message":"invalid or expired jwt"}`が返ってくる。
- [x]  `curl -H 'Authorization:Bearer "ログイン時に得られるアクセストークン"' http://localhost:8080/allowed/users/"文字列" `を実行して、`{"error":"Page is not type int"}`が返ってくる。
- [x]  `curl -H 'Authorization:Bearer "ログイン時に得られるアクセストークン"' http://localhost:8080/allowed/users/"存在しないページ" `を実行して、`null`が返ってくる。

- Admin権限がないユーザーがログインした時
- [x]  ` curl -X POST -H "Content-Type: application/json" -d '{"Email":"kentaro.suzuki@persol-pt.co.jp", "Password":"kentaro379"}' http://localhost:8080/login` を実行して、`{"email":"kentaro.suzuki@persol-pt.co.jp","name":"鈴木健太郎","isAdmin":0,"access_token":"有効期限1時間のアクセストークン"}` が返ってくる。
- [x]  `curl -H 'Authorization:Bearer "上記ログイン時に得られるアクセストークン"' http://localhost:8080/allowed/users/1 `を実行して、`{"error":"isAdmin Certification is invalid"}` が返ってくる。

- ログインせずにアクセスした時
- [x]  `curl http://localhost:8080/allowed/users/1`を実行して、`{"message":"missing or malformed jwt"}` が返ってくる。


## 関連URL

- https://echo.labstack.com/docs/request
- https://echo.labstack.com/docs/testing

## 備考

- 特になし

2024-01-29 02:34 UTC, jusui-ppt approved these changes
![LGTM](https://images.lgtmgen.org/eb53fd05-d74c-408a-8a66-2114d92d7400)

2024-01-29 02:49 UTC, tarokamikaze approved these changes
LGTM!

2024-01-29 02:49 UTC, merged